- id: '1536607265961'
  alias: Nattlampor på
  trigger:
  - event: sunset
    offset: '-15'
    platform: sun
  - at: 05:00
    platform: time
  condition: []
  action:
  - alias: ''
    data:
      brightness: 40
      entity_id: group.nlhue
    service: homeassistant.turn_on
  - data:
      entity_id: group.nlzw
    service: switch.turn_on
- id: '1536607441102'
  alias: Nattlampor av
  trigger:
  - event: sunrise
    offset: '10'
    platform: sun
  - at: 00:00
    platform: time
  - at: 08:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.nattlampor
    service: homeassistant.turn_off
  - data:
      entity_id: switch.telldus_tzwp100_plugin_switch_switch_2
    service: switch.turn_off
- id: '1536608356759'
  alias: Akvarium på
  trigger:
  - at: '11:30'
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.akvarium
    service: switch.turn_on
- id: '1536608437040'
  alias: Akvarium av
  trigger:
  - at: '19:30'
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.akvarium
    service: switch.turn_off
- action:
  - data:
      entity_id: group.entre
      transition: 15
    service: homeassistant.turn_off
  alias: Sensor hallen av
  id: '1516528117333'
  trigger:
  - entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor
    for: 00:03:00
    platform: state
    to: 'off'
- id: '1516526519801'
  alias: Sensor hallen på
  trigger:
  - entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor
    platform: state
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ states.sun.sun.attributes.elevation < 3 }}'
  action:
  - data:
      entity_id: group.entre
    data_template:
      brightness: '{{states.sun.sun.attributes.elevation | int * 4 + 200}}'
    service: homeassistant.turn_on
- id: '1540752390473'
  alias: Motorvärmare på
  trigger:
  - at: 05:30
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.fibaro_system_fgwpef_wall_plug_switch_4
    service: switch.turn_on
- id: '1540752501830'
  alias: Motorvärmare av
  trigger:
  - at: 08:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.fibaro_system_fgwpef_wall_plug_switch_4
    service: switch.turn_off
- id: '1540752600292'
  alias: Utelampor på
  trigger:
  - event: sunset
    offset: '20'
    platform: sun
  condition: []
  action:
  - data:
      entity_id:
    service: homeassistant.turn_on
- id: '1540752706428'
  alias: Utelampor
  trigger:
  - event: sunrise
    offset: '-10'
    platform: sun
  condition: []
  action:
  - data:
      entity_id:
    service: homeassistant.turn_off
- id: '1541431368483'
  alias: Barnsovrum fönsterlampa på
  trigger:
  - event: sunset
    offset: '-15'
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.telldus_tzwp100_plugin_switch_switch_2
    service: switch.turn_on
- id: '1541431456616'
  alias: Barnsovrum fönsterlampa av
  trigger:
  - at: '19:45'
    platform: time
  - at: 08:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.telldus_tzwp100_plugin_switch_switch_2
    service: switch.turn_off
- id: '1541431702857'
  alias: Barnsovrum fönsterlampa på morgon
  trigger:
  - at: 06:45
    platform: time
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: switch.telldus_tzwp100_plugin_switch_switch_2
    service: switch.turn_on
- id: '1583263433458'
  alias: Nattlampa sovrum
  trigger:
  - entity_id: light.sovrum_2
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '20:00'
    before: 03:00
    condition: time
  action:
  - data:
      brightness: 40
      entity_id: light.sovrum_2
    service: homeassistant.turn_on
