- action:
  - service: switch.turn_on
    data:
      entity_id: group.akvarium
  alias: Akvarium on
  condition: []
  id: '1513456575113'
  trigger:
  - at: 09:30
    platform: time
- action:
  - service: homeassistant.turn_off
    data:
      entity_id: group.akvarium
  alias: Akvarium Off
  condition: []
  id: '1513458015193'
  trigger:
  - at: '19:00'
    platform: time
- action:
  - data:
      entity_id: group.nattlampor
    service: homeassistant.turn_on
  alias: 'Nattlampor på '
  condition: []
  id: '1513471472905'
  trigger:
  - event: sunset
    platform: sun
  - at: 05:00
    platform: time
- action:
  - data:
      entity_id: group.nattlampor
    service: homeassistant.turn_off
  alias: Nattlampor av
  condition: []
  id: '1513471571410'
  trigger:
  - at: 00:00
    platform: time
  - event: sunrise
    platform: sun
  - at: 09:00
    platform: time
- action:
  - data:
      entity_id: switch.switch_6
    service: switch.turn_on
  alias: Barnsovrum fönsterlampa på
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  id: '1513526053354'
  trigger:
  - at: 06:45
    platform: time
- action:
  - data:
      entity_id: switch.switch_6
    service: switch.turn_off
  alias: Barnsovrum fönsterlampa av
  condition: []
  id: '1513526396033'
  trigger:
  - at: '19:45'
    platform: time
  - event: sunrise
    offset: 00:30:00
    platform: sun
  - at: 08:00
    platform: time
- action:
  - data:
      entity_id: switch.switch_8
    service: homeassistant.turn_on
  alias: Motorvärmare på
  condition: []
  id: '1513639483915'
  trigger:
  - at: 05:30
    platform: time
- action:
  - data:
      entity_id: switch.switch_8
    service: homeassistant.turn_off
  alias: Motorvärmare av
  condition: []
  id: '1513639537081'
  trigger:
  - at: '8:00'
    platform: time
- action:
  - data:
      entity_id: switch.switch_6
    service: homeassistant.turn_on
  alias: Barnsovrum fönsterlampa på kväll
  condition: []
  id: '1516525857892'
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
- action:
  - data:
      brightness: 200
      entity_id: group.entre
    service: homeassistant.turn_on
  alias: Sensor hallen på
  condition:
  - condition: template
    value_template: '{{ states.sun.sun.attributes.elevation < 2 }}'
  id: '1516526519801'
  trigger:
  - entity_id: binary_sensor.sensor
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: group.entre
      transition: 15
    service: homeassistant.turn_off
  alias: Sensor hallen av
  id: '1516528117333'
  trigger:
  - entity_id: binary_sensor.sensor
    for: 00:03:00
    platform: state
    to: 'off'
- action:
  - data:
      message: Rörelse i hallen
    service: notify.pushbullet
  alias: Larm test
  condition:
  - after: 08:00
    before: '16:00'
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  id: '1516551013433'
  trigger:
  - entity_id: binary_sensor.bollen_sensor
    platform: state
    to: 'on'
- action:
  - data:
      brightness: 175
      kelvin: 2700
      entity_id: light.barnsovrum_rgb
    service: light.turn_on
  alias: Sovdags barn on
  condition: []
  id: '1518723121672'
  trigger:
  - at: '19:15'
    platform: time
- action:
  - service: light.turn_off
    data:
      entity_id: light.barnsovrum_rgb
      transition: 899
  alias: Sovdags barn dimma
  condition: []
  id: '1518723683892'
  trigger:
  - at: '19:45'
    platform: time
- action:
  - service: light.hue_activate_scene
    data:
      group_name: Barnsovrum
      scene_name: Nightlight
  alias: Sovdags barn nattlampa
  condition: []
  id: '1518725681480'
  trigger:
  - at: '20:00'
    platform: time
- action:
  - service: light.turn_off
    data:
      entity_id: light.barnsovrum_rgb
  alias: Sovdags barn nattlampa av
  condition: []
  id: '1518726278721'
  trigger:
  - at: '21:00'
    platform: time
- action:
  - data:
      activity: 25940701
      entity_id: remote.harmony_hub
    service: remote.turn_on
  alias: Chromecast trigger
  condition:
  - condition: template
    value_template: '{{ states.remote.harmony_hub.attributes.current_activity != 25940701
      }}'
  id: '1518947206385'
  trigger:
  - entity_id: media_player.vardagsrum
    platform: state
    to: playing
